name: End-2-End Android

on: [push]

jobs:

  detox:

    runs-on: macos-latest

    defaults:
      run:
        shell: bash
        working-directory: BrightID

    strategy:
      matrix:
        node-version: [12.x]
        api-level: [29]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        id: yarn-cache-debug # needed below to check for cache hit or miss
        uses: actions/cache@v2
        with:
          path: './BrightID/node_modules'
          key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('./BrightID/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache-debug.outputs.cache-hit != 'true'  # only install when no cache found
        run: yarn --frozen-lockfile

      - name: detox build
        run: |
          mv ./android/app/google-services.json-dev ./android/app/google-services.json
          yarn build:detox:android

      - name: run detox tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          avd-name: Pixel_2_XL_API_28
          script: yarn start:detox & yarn test:android -- --headless
